# --- !Ups

CREATE TABLE "USER" (
  "LOGIN"   VARCHAR(200) PRIMARY KEY,
  "BALANCE" DECIMAL(20, 2) NOT NULL
);
INSERT INTO "USER" VALUES ('user1@mail.com', 100.51);
INSERT INTO "USER" VALUES ('user2@mail.com', 200.51);
INSERT INTO "USER" VALUES ('user3@mail.com', 300.51);

CREATE TABLE "TRANSACTION" (
  "ID"               BIGINT AUTO_INCREMENT PRIMARY KEY,
  "USER_LOGIN"       VARCHAR(200),
  "TRANSACTION_TYPE" VARCHAR(20),
  "AMOUNT"           DECIMAL(20, 2),
  "DATE"             TIMESTAMP,
  "IS_SUCCESSFUL"    BOOLEAN
);
INSERT INTO "TRANSACTION" (USER_LOGIN, TRANSACTION_TYPE, AMOUNT, DATE, IS_SUCCESSFUL)
VALUES ('user1@mail.com', 'DEBIT', 100, CURRENT_TIMESTAMP(), TRUE);
INSERT INTO "TRANSACTION" (USER_LOGIN, TRANSACTION_TYPE, AMOUNT, DATE, IS_SUCCESSFUL)
VALUES ('user1@mail.com', 'DEBIT', 200, CURRENT_TIMESTAMP(), TRUE);
INSERT INTO "TRANSACTION" (USER_LOGIN, TRANSACTION_TYPE, AMOUNT, DATE, IS_SUCCESSFUL)
VALUES ('user1@mail.com', 'DEBIT', 300, CURRENT_TIMESTAMP(), TRUE);
INSERT INTO "TRANSACTION" (USER_LOGIN, TRANSACTION_TYPE, AMOUNT, DATE, IS_SUCCESSFUL)
VALUES ('user1@mail.com', 'CREDIT', 500, CURRENT_TIMESTAMP(), TRUE);

# --- !Downs

DROP TABLE "TRANSACTION";
DROP TABLE "USER";